extern crate cc;
extern crate git2;

use std::env;
use std::path::{PathBuf};

use git2::{Repository, ErrorCode};


fn main() {
    let bearssl_dir = env::var("BEARSSL_DIR");
    let use_git = bearssl_dir.is_err();

    let mut bearssl_root = PathBuf::from(&bearssl_dir.unwrap_or(env::var("OUT_DIR").unwrap()));

    if use_git {
        let repo_exists = if env::var_os("BEARSSL_BUILD_DBG").is_some() {
            Repository::discover(&bearssl_root).is_ok()
        } else {
            false
        };

        if !repo_exists {
            bearssl_root = bearssl_root.join("bearssl");
            let url = "https://www.bearssl.org/git/BearSSL";
            let repo = match Repository::clone(url, &bearssl_root) {
                Ok(repo) => repo,
                Err(e) => {
                    panic!("failed to clone BearSSL from {}: {}", url, e)
                },
            };
        } else {
            bearssl_root = bearssl_root.join("bearssl");
            println!("Build debug mode: using existing BearSSL repo.");
        }
    }

    // https://github.com/alexcrichton/cc-rs/issues/253
    // Sigh... split into 3 libraries as a workaround on Windows...
    let cc = cc::Build::new()
        .files([
            bearssl_root.join("src/settings.c"),
            bearssl_root.join("src/aead/ccm.c"),
            bearssl_root.join("src/aead/eax.c"),
            bearssl_root.join("src/aead/gcm.c"),
            bearssl_root.join("src/codec/ccopy.c"),
            bearssl_root.join("src/codec/dec16be.c"),
            bearssl_root.join("src/codec/dec16le.c"),
            bearssl_root.join("src/codec/dec32be.c"),
            bearssl_root.join("src/codec/dec32le.c"),
            bearssl_root.join("src/codec/dec64be.c"),
            bearssl_root.join("src/codec/dec64le.c"),
            bearssl_root.join("src/codec/enc16be.c"),
            bearssl_root.join("src/codec/enc16le.c"),
            bearssl_root.join("src/codec/enc32be.c"),
            bearssl_root.join("src/codec/enc32le.c"),
            bearssl_root.join("src/codec/enc64be.c"),
            bearssl_root.join("src/codec/enc64le.c"),
            bearssl_root.join("src/codec/pemdec.c"),
            bearssl_root.join("src/codec/pemenc.c"),
            bearssl_root.join("src/ec/ec_all_m15.c"),
            bearssl_root.join("src/ec/ec_all_m31.c"),
            bearssl_root.join("src/ec/ec_c25519_i15.c"),
            bearssl_root.join("src/ec/ec_c25519_i31.c"),
            bearssl_root.join("src/ec/ec_c25519_m15.c"),
            bearssl_root.join("src/ec/ec_c25519_m31.c"),
            bearssl_root.join("src/ec/ec_c25519_m62.c"),
            bearssl_root.join("src/ec/ec_c25519_m64.c"),
            bearssl_root.join("src/ec/ec_curve25519.c"),
            bearssl_root.join("src/ec/ec_default.c"),
            bearssl_root.join("src/ec/ec_keygen.c"),
            bearssl_root.join("src/ec/ec_p256_m15.c"),
            bearssl_root.join("src/ec/ec_p256_m31.c"),
            bearssl_root.join("src/ec/ec_p256_m62.c"),
            bearssl_root.join("src/ec/ec_p256_m64.c"),
            bearssl_root.join("src/ec/ec_prime_i15.c"),
            bearssl_root.join("src/ec/ec_prime_i31.c"),
            bearssl_root.join("src/ec/ec_pubkey.c"),
            bearssl_root.join("src/ec/ec_secp256r1.c"),
            bearssl_root.join("src/ec/ec_secp384r1.c"),
            bearssl_root.join("src/ec/ec_secp521r1.c"),
            bearssl_root.join("src/ec/ecdsa_atr.c"),
            bearssl_root.join("src/ec/ecdsa_default_sign_asn1.c"),
            bearssl_root.join("src/ec/ecdsa_default_sign_raw.c"),
            bearssl_root.join("src/ec/ecdsa_default_vrfy_asn1.c"),
            bearssl_root.join("src/ec/ecdsa_default_vrfy_raw.c"),
            bearssl_root.join("src/ec/ecdsa_i15_bits.c"),
            bearssl_root.join("src/ec/ecdsa_i15_sign_asn1.c"),
            bearssl_root.join("src/ec/ecdsa_i15_sign_raw.c"),
            bearssl_root.join("src/ec/ecdsa_i15_vrfy_asn1.c"),
            bearssl_root.join("src/ec/ecdsa_i15_vrfy_raw.c"),
            bearssl_root.join("src/ec/ecdsa_i31_bits.c"),
            bearssl_root.join("src/ec/ecdsa_i31_sign_asn1.c"),
            bearssl_root.join("src/ec/ecdsa_i31_sign_raw.c"),
            bearssl_root.join("src/ec/ecdsa_i31_vrfy_asn1.c"),
            bearssl_root.join("src/ec/ecdsa_i31_vrfy_raw.c"),
            bearssl_root.join("src/ec/ecdsa_rta.c")
        ].iter())
            .include(bearssl_root.join("inc"))
            .include(bearssl_root.join("src"))
            .compile("bearssl-ae");

    let cc = cc::Build::new()
        .files([
            bearssl_root.join("src/hash/dig_oid.c"),
            bearssl_root.join("src/hash/dig_size.c"),
            bearssl_root.join("src/hash/ghash_ctmul.c"),
            bearssl_root.join("src/hash/ghash_ctmul32.c"),
            bearssl_root.join("src/hash/ghash_ctmul64.c"),
            bearssl_root.join("src/hash/ghash_pclmul.c"),
            bearssl_root.join("src/hash/ghash_pwr8.c"),
            bearssl_root.join("src/hash/md5.c"),
            bearssl_root.join("src/hash/md5sha1.c"),
            bearssl_root.join("src/hash/mgf1.c"),
            bearssl_root.join("src/hash/multihash.c"),
            bearssl_root.join("src/hash/sha1.c"),
            bearssl_root.join("src/hash/sha2big.c"),
            bearssl_root.join("src/hash/sha2small.c"),
            bearssl_root.join("src/int/i15_add.c"),
            bearssl_root.join("src/int/i15_bitlen.c"),
            bearssl_root.join("src/int/i15_decmod.c"),
            bearssl_root.join("src/int/i15_decode.c"),
            bearssl_root.join("src/int/i15_decred.c"),
            bearssl_root.join("src/int/i15_encode.c"),
            bearssl_root.join("src/int/i15_fmont.c"),
            bearssl_root.join("src/int/i15_iszero.c"),
            bearssl_root.join("src/int/i15_moddiv.c"),
            bearssl_root.join("src/int/i15_modpow.c"),
            bearssl_root.join("src/int/i15_modpow2.c"),
            bearssl_root.join("src/int/i15_montmul.c"),
            bearssl_root.join("src/int/i15_mulacc.c"),
            bearssl_root.join("src/int/i15_muladd.c"),
            bearssl_root.join("src/int/i15_ninv15.c"),
            bearssl_root.join("src/int/i15_reduce.c"),
            bearssl_root.join("src/int/i15_rshift.c"),
            bearssl_root.join("src/int/i15_sub.c"),
            bearssl_root.join("src/int/i15_tmont.c"),
            bearssl_root.join("src/int/i31_add.c"),
            bearssl_root.join("src/int/i31_bitlen.c"),
            bearssl_root.join("src/int/i31_decmod.c"),
            bearssl_root.join("src/int/i31_decode.c"),
            bearssl_root.join("src/int/i31_decred.c"),
            bearssl_root.join("src/int/i31_encode.c"),
            bearssl_root.join("src/int/i31_fmont.c"),
            bearssl_root.join("src/int/i31_iszero.c"),
            bearssl_root.join("src/int/i31_moddiv.c"),
            bearssl_root.join("src/int/i31_modpow.c"),
            bearssl_root.join("src/int/i31_modpow2.c"),
            bearssl_root.join("src/int/i31_montmul.c"),
            bearssl_root.join("src/int/i31_mulacc.c"),
            bearssl_root.join("src/int/i31_muladd.c"),
            bearssl_root.join("src/int/i31_ninv31.c"),
            bearssl_root.join("src/int/i31_reduce.c"),
            bearssl_root.join("src/int/i31_rshift.c"),
            bearssl_root.join("src/int/i31_sub.c"),
            bearssl_root.join("src/int/i31_tmont.c"),
            bearssl_root.join("src/int/i32_add.c"),
            bearssl_root.join("src/int/i32_bitlen.c"),
            bearssl_root.join("src/int/i32_decmod.c"),
            bearssl_root.join("src/int/i32_decode.c"),
            bearssl_root.join("src/int/i32_decred.c"),
            bearssl_root.join("src/int/i32_div32.c"),
            bearssl_root.join("src/int/i32_encode.c"),
            bearssl_root.join("src/int/i32_fmont.c"),
            bearssl_root.join("src/int/i32_iszero.c"),
            bearssl_root.join("src/int/i32_modpow.c"),
            bearssl_root.join("src/int/i32_montmul.c"),
            bearssl_root.join("src/int/i32_mulacc.c"),
            bearssl_root.join("src/int/i32_muladd.c"),
            bearssl_root.join("src/int/i32_ninv32.c"),
            bearssl_root.join("src/int/i32_reduce.c"),
            bearssl_root.join("src/int/i32_sub.c"),
            bearssl_root.join("src/int/i32_tmont.c"),
            bearssl_root.join("src/int/i62_modpow2.c"),
            bearssl_root.join("src/kdf/hkdf.c"),
            bearssl_root.join("src/kdf/shake.c"),
            bearssl_root.join("src/mac/hmac.c"),
            bearssl_root.join("src/mac/hmac_ct.c"),
            bearssl_root.join("src/rand/aesctr_drbg.c"),
            bearssl_root.join("src/rand/hmac_drbg.c"),
            bearssl_root.join("src/rand/sysrng.c"),
            bearssl_root.join("src/rsa/rsa_default_keygen.c"),
            bearssl_root.join("src/rsa/rsa_default_modulus.c"),
            bearssl_root.join("src/rsa/rsa_default_oaep_decrypt.c"),
            bearssl_root.join("src/rsa/rsa_default_oaep_encrypt.c"),
            bearssl_root.join("src/rsa/rsa_default_pkcs1_sign.c"),
            bearssl_root.join("src/rsa/rsa_default_pkcs1_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_default_priv.c"),
            bearssl_root.join("src/rsa/rsa_default_privexp.c"),
            bearssl_root.join("src/rsa/rsa_default_pss_sign.c"),
            bearssl_root.join("src/rsa/rsa_default_pss_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_default_pub.c"),
            bearssl_root.join("src/rsa/rsa_default_pubexp.c"),
            bearssl_root.join("src/rsa/rsa_i15_keygen.c"),
            bearssl_root.join("src/rsa/rsa_i15_modulus.c"),
            bearssl_root.join("src/rsa/rsa_i15_oaep_decrypt.c"),
            bearssl_root.join("src/rsa/rsa_i15_oaep_encrypt.c"),
            bearssl_root.join("src/rsa/rsa_i15_pkcs1_sign.c"),
            bearssl_root.join("src/rsa/rsa_i15_pkcs1_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i15_priv.c"),
            bearssl_root.join("src/rsa/rsa_i15_privexp.c"),
            bearssl_root.join("src/rsa/rsa_i15_pss_sign.c"),
            bearssl_root.join("src/rsa/rsa_i15_pss_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i15_pub.c"),
            bearssl_root.join("src/rsa/rsa_i15_pubexp.c"),
            bearssl_root.join("src/rsa/rsa_i31_keygen.c"),
            bearssl_root.join("src/rsa/rsa_i31_keygen_inner.c"),
            bearssl_root.join("src/rsa/rsa_i31_modulus.c"),
            bearssl_root.join("src/rsa/rsa_i31_oaep_decrypt.c"),
            bearssl_root.join("src/rsa/rsa_i31_oaep_encrypt.c"),
            bearssl_root.join("src/rsa/rsa_i31_pkcs1_sign.c"),
            bearssl_root.join("src/rsa/rsa_i31_pkcs1_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i31_priv.c"),
            bearssl_root.join("src/rsa/rsa_i31_privexp.c"),
            bearssl_root.join("src/rsa/rsa_i31_pss_sign.c"),
            bearssl_root.join("src/rsa/rsa_i31_pss_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i31_pub.c"),
            bearssl_root.join("src/rsa/rsa_i31_pubexp.c"),
            bearssl_root.join("src/rsa/rsa_i32_oaep_decrypt.c"),
            bearssl_root.join("src/rsa/rsa_i32_oaep_encrypt.c"),
            bearssl_root.join("src/rsa/rsa_i32_pkcs1_sign.c"),
            bearssl_root.join("src/rsa/rsa_i32_pkcs1_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i32_priv.c"),
            bearssl_root.join("src/rsa/rsa_i32_pss_sign.c"),
            bearssl_root.join("src/rsa/rsa_i32_pss_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i32_pub.c"),
            bearssl_root.join("src/rsa/rsa_i62_keygen.c"),
            bearssl_root.join("src/rsa/rsa_i62_oaep_decrypt.c"),
            bearssl_root.join("src/rsa/rsa_i62_oaep_encrypt.c"),
            bearssl_root.join("src/rsa/rsa_i62_pkcs1_sign.c"),
            bearssl_root.join("src/rsa/rsa_i62_pkcs1_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i62_priv.c"),
            bearssl_root.join("src/rsa/rsa_i62_pss_sign.c"),
            bearssl_root.join("src/rsa/rsa_i62_pss_vrfy.c"),
            bearssl_root.join("src/rsa/rsa_i62_pub.c"),
            bearssl_root.join("src/rsa/rsa_oaep_pad.c"),
            bearssl_root.join("src/rsa/rsa_oaep_unpad.c"),
            bearssl_root.join("src/rsa/rsa_pkcs1_sig_pad.c"),
            bearssl_root.join("src/rsa/rsa_pkcs1_sig_unpad.c"),
            bearssl_root.join("src/rsa/rsa_pss_sig_pad.c"),
            bearssl_root.join("src/rsa/rsa_pss_sig_unpad.c"),
            bearssl_root.join("src/rsa/rsa_ssl_decrypt.c"),
        ].iter())
            .include(bearssl_root.join("inc"))
            .include(bearssl_root.join("src"))
            .compile("bearssl-hr");

    let cc3 = cc::Build::new()
        .files([
            bearssl_root.join("src/ssl/prf.c"),
            bearssl_root.join("src/ssl/prf_md5sha1.c"),
            bearssl_root.join("src/ssl/prf_sha256.c"),
            bearssl_root.join("src/ssl/prf_sha384.c"),
            bearssl_root.join("src/ssl/ssl_ccert_single_ec.c"),
            bearssl_root.join("src/ssl/ssl_ccert_single_rsa.c"),
            bearssl_root.join("src/ssl/ssl_client.c"),
            bearssl_root.join("src/ssl/ssl_client_default_rsapub.c"),
            bearssl_root.join("src/ssl/ssl_client_full.c"),
            bearssl_root.join("src/ssl/ssl_engine.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_aescbc.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_aesccm.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_aesgcm.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_chapol.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_descbc.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_ec.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_ecdsa.c"),
            bearssl_root.join("src/ssl/ssl_engine_default_rsavrfy.c"),
            bearssl_root.join("src/ssl/ssl_hashes.c"),
            bearssl_root.join("src/ssl/ssl_hs_client.c"),
            bearssl_root.join("src/ssl/ssl_hs_server.c"),
            bearssl_root.join("src/ssl/ssl_io.c"),
            bearssl_root.join("src/ssl/ssl_keyexport.c"),
            bearssl_root.join("src/ssl/ssl_lru.c"),
            bearssl_root.join("src/ssl/ssl_rec_cbc.c"),
            bearssl_root.join("src/ssl/ssl_rec_ccm.c"),
            bearssl_root.join("src/ssl/ssl_rec_chapol.c"),
            bearssl_root.join("src/ssl/ssl_rec_gcm.c"),
            bearssl_root.join("src/ssl/ssl_scert_single_ec.c"),
            bearssl_root.join("src/ssl/ssl_scert_single_rsa.c"),
            bearssl_root.join("src/ssl/ssl_server.c"),
            bearssl_root.join("src/ssl/ssl_server_full_ec.c"),
            bearssl_root.join("src/ssl/ssl_server_full_rsa.c"),
            bearssl_root.join("src/ssl/ssl_server_mine2c.c"),
            bearssl_root.join("src/ssl/ssl_server_mine2g.c"),
            bearssl_root.join("src/ssl/ssl_server_minf2c.c"),
            bearssl_root.join("src/ssl/ssl_server_minf2g.c"),
            bearssl_root.join("src/ssl/ssl_server_minr2g.c"),
            bearssl_root.join("src/ssl/ssl_server_minu2g.c"),
            bearssl_root.join("src/ssl/ssl_server_minv2g.c"),
            bearssl_root.join("src/symcipher/aes_big_cbcdec.c"),
            bearssl_root.join("src/symcipher/aes_big_cbcenc.c"),
            bearssl_root.join("src/symcipher/aes_big_ctr.c"),
            bearssl_root.join("src/symcipher/aes_big_ctrcbc.c"),
            bearssl_root.join("src/symcipher/aes_big_dec.c"),
            bearssl_root.join("src/symcipher/aes_big_enc.c"),
            bearssl_root.join("src/symcipher/aes_common.c"),
            bearssl_root.join("src/symcipher/aes_ct.c"),
            bearssl_root.join("src/symcipher/aes_ct64.c"),
            bearssl_root.join("src/symcipher/aes_ct64_cbcdec.c"),
            bearssl_root.join("src/symcipher/aes_ct64_cbcenc.c"),
            bearssl_root.join("src/symcipher/aes_ct64_ctr.c"),
            bearssl_root.join("src/symcipher/aes_ct64_ctrcbc.c"),
            bearssl_root.join("src/symcipher/aes_ct64_dec.c"),
            bearssl_root.join("src/symcipher/aes_ct64_enc.c"),
            bearssl_root.join("src/symcipher/aes_ct_cbcdec.c"),
            bearssl_root.join("src/symcipher/aes_ct_cbcenc.c"),
            bearssl_root.join("src/symcipher/aes_ct_ctr.c"),
            bearssl_root.join("src/symcipher/aes_ct_ctrcbc.c"),
            bearssl_root.join("src/symcipher/aes_ct_dec.c"),
            bearssl_root.join("src/symcipher/aes_ct_enc.c"),
            bearssl_root.join("src/symcipher/aes_pwr8.c"),
            bearssl_root.join("src/symcipher/aes_pwr8_cbcdec.c"),
            bearssl_root.join("src/symcipher/aes_pwr8_cbcenc.c"),
            bearssl_root.join("src/symcipher/aes_pwr8_ctr.c"),
            bearssl_root.join("src/symcipher/aes_pwr8_ctrcbc.c"),
            bearssl_root.join("src/symcipher/aes_small_cbcdec.c"),
            bearssl_root.join("src/symcipher/aes_small_cbcenc.c"),
            bearssl_root.join("src/symcipher/aes_small_ctr.c"),
            bearssl_root.join("src/symcipher/aes_small_ctrcbc.c"),
            bearssl_root.join("src/symcipher/aes_small_dec.c"),
            bearssl_root.join("src/symcipher/aes_small_enc.c"),
            bearssl_root.join("src/symcipher/aes_x86ni.c"),
            bearssl_root.join("src/symcipher/aes_x86ni_cbcdec.c"),
            bearssl_root.join("src/symcipher/aes_x86ni_cbcenc.c"),
            bearssl_root.join("src/symcipher/aes_x86ni_ctr.c"),
            bearssl_root.join("src/symcipher/aes_x86ni_ctrcbc.c"),
            bearssl_root.join("src/symcipher/chacha20_ct.c"),
            bearssl_root.join("src/symcipher/chacha20_sse2.c"),
            bearssl_root.join("src/symcipher/des_ct.c"),
            bearssl_root.join("src/symcipher/des_ct_cbcdec.c"),
            bearssl_root.join("src/symcipher/des_ct_cbcenc.c"),
            bearssl_root.join("src/symcipher/des_support.c"),
            bearssl_root.join("src/symcipher/des_tab.c"),
            bearssl_root.join("src/symcipher/des_tab_cbcdec.c"),
            bearssl_root.join("src/symcipher/des_tab_cbcenc.c"),
            bearssl_root.join("src/symcipher/poly1305_ctmul.c"),
            bearssl_root.join("src/symcipher/poly1305_ctmul32.c"),
            bearssl_root.join("src/symcipher/poly1305_ctmulq.c"),
            bearssl_root.join("src/symcipher/poly1305_i15.c"),
            bearssl_root.join("src/x509/asn1enc.c"),
            bearssl_root.join("src/x509/encode_ec_pk8der.c"),
            bearssl_root.join("src/x509/encode_ec_rawder.c"),
            bearssl_root.join("src/x509/encode_rsa_pk8der.c"),
            bearssl_root.join("src/x509/encode_rsa_rawder.c"),
            bearssl_root.join("src/x509/skey_decoder.c"),
            bearssl_root.join("src/x509/x509_decoder.c"),
            bearssl_root.join("src/x509/x509_knownkey.c"),
            bearssl_root.join("src/x509/x509_minimal.c"),
            bearssl_root.join("src/x509/x509_minimal_full.c"),
        ].iter())
            .include(bearssl_root.join("inc"))
            .include(bearssl_root.join("src"))
            .compile("bearssl-sx");
}
